"""Initial inventory schema"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "721e69034285"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_audit",
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("request_id", sa.String(length=36), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_audit")),
        schema="inventory",
    )
    op.create_table(
        "gpu_slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner", sa.String(length=36), nullable=True),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("fencing_token", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gpu_slots")),
        schema="inventory",
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("operation_scope", sa.String(length=120), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "response",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_keys")),
        sa.UniqueConstraint(
            "user_id",
            "workspace_id",
            "operation_scope",
            "key",
            name=op.f("uq_idempotency_keys_user_id_workspace_id_operation_scope_key"),
        ),
        schema="inventory",
    )
    op.create_table(
        "login_attempts",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_login_attempts")),
        schema="inventory",
    )
    op.create_table(
        "model_cooldowns",
        sa.Column("quota_key", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.Column("reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_cooldowns")),
        sa.UniqueConstraint("quota_key", name=op.f("uq_model_cooldowns_quota_key")),
        schema="inventory",
    )
    op.create_table(
        "model_deployments",
        sa.Column("logical_name", sa.String(length=50), nullable=False),
        sa.Column("actual_model_id", sa.String(length=255), nullable=False),
        sa.Column("endpoint_ref", sa.String(length=50), nullable=False),
        sa.Column("credential_ref", sa.String(length=50), nullable=True),
        sa.Column("trust_domain", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("maintenance", sa.Boolean(), nullable=False),
        sa.Column(
            "capabilities",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_deployments")),
        sa.UniqueConstraint("logical_name", name=op.f("uq_model_deployments_logical_name")),
        schema="inventory",
    )
    op.create_table(
        "runtime_controls",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column(
            "value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_runtime_controls")),
        schema="inventory",
    )
    op.create_table(
        "users",
        sa.Column("login", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("app_role", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("auth_version", sa.Integer(), nullable=False),
        sa.Column(
            "preferences",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("preferences_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("login", name=op.f("uq_users_login")),
        schema="inventory",
    )
    op.create_table(
        "agreements",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("agreement_type", sa.String(length=50), nullable=False),
        sa.Column("agreement_version", sa.String(length=50), nullable=False),
        sa.Column(
            "acceptance_context",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["inventory.users.id"], name=op.f("fk_agreements_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agreements")),
        sa.UniqueConstraint(
            "user_id",
            "agreement_type",
            "agreement_version",
            name=op.f("uq_agreements_user_id_agreement_type_agreement_version"),
        ),
        schema="inventory",
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["inventory.users.id"], name=op.f("fk_sessions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("refresh_token_hash", name=op.f("uq_sessions_refresh_token_hash")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_sessions_family_id"), "sessions", ["family_id"], unique=False, schema="inventory"
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False, schema="inventory")
    op.create_table(
        "settings_revisions",
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("previous_revision", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "components_pending",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["inventory.users.id"], name=op.f("fk_settings_revisions_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings_revisions")),
        sa.UniqueConstraint("revision", name=op.f("uq_settings_revisions_revision")),
        schema="inventory",
    )
    op.create_table(
        "workspaces",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"], ["inventory.users.id"], name=op.f("fk_workspaces_owner_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
        schema="inventory",
    )
    op.create_table(
        "deletion_tombstones",
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["inventory.workspaces.id"],
            name=op.f("fk_deletion_tombstones_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deletion_tombstones")),
        sa.UniqueConstraint(
            "entity_type", "entity_id", name=op.f("uq_deletion_tombstones_entity_type_entity_id")
        ),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_deletion_tombstones_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_deletion_tombstones_workspace_id"),
        "deletion_tombstones",
        ["workspace_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "field_evidence",
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("field_key", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("media_id", sa.String(length=36), nullable=True),
        sa.Column(
            "region",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("raw_value", sa.Text(), nullable=True),
        sa.Column(
            "normalized_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("verification_state", sa.String(length=20), nullable=False),
        sa.Column("proposal_id", sa.String(length=36), nullable=False),
        sa.Column("model_revision", sa.String(length=100), nullable=True),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["inventory.workspaces.id"],
            name=op.f("fk_field_evidence_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_evidence")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_field_evidence_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_field_evidence_workspace_id"),
        "field_evidence",
        ["workspace_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "inbox_notifications",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("dedupe_key", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "subjects",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snoozed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["inventory.users.id"], name=op.f("fk_inbox_notifications_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["inventory.workspaces.id"],
            name=op.f("fk_inbox_notifications_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbox_notifications")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_inbox_notifications_dedupe_key")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_inbox_notifications_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_inbox_notifications_user_id"),
        "inbox_notifications",
        ["user_id"],
        unique=False,
        schema="inventory",
    )
    op.create_index(
        op.f("ix_inbox_notifications_workspace_id"),
        "inbox_notifications",
        ["workspace_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "ingestion_batches",
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["inventory.users.id"], name=op.f("fk_ingestion_batches_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["inventory.workspaces.id"],
            name=op.f("fk_ingestion_batches_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_batches")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_ingestion_batches_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_ingestion_batches_workspace_id"),
        "ingestion_batches",
        ["workspace_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "items",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("primary_category", sa.String(length=30), nullable=False),
        sa.Column(
            "secondary_categories",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("tracking_mode", sa.String(length=20), nullable=False),
        sa.Column("base_unit_id", sa.String(length=30), nullable=True),
        sa.Column("quantity_step", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("attributes_schema_version", sa.String(length=30), nullable=False),
        sa.Column("barcode", sa.String(length=100), nullable=True),
        sa.Column("brand", sa.String(length=255), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("user_description", sa.Text(), nullable=True),
        sa.Column("generated_description", sa.Text(), nullable=True),
        sa.Column("description_model_revision", sa.String(length=100), nullable=True),
        sa.Column("privacy_policy", sa.String(length=20), nullable=False),
        sa.Column("lifecycle", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("search_revision", sa.BigInteger(), nullable=False),
        sa.Column("indexed_revision", sa.BigInteger(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "primary_category != 'document' OR privacy_policy = 'local_only'",
            name=op.f("ck_items_private_document"),
        ),
        sa.CheckConstraint("quantity_step > 0", name=op.f("ck_items_positive_step")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["inventory.users.id"], name=op.f("fk_items_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["inventory.workspaces.id"], name=op.f("fk_items_workspace_id_workspaces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_items_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(op.f("ix_items_barcode"), "items", ["barcode"], unique=False, schema="inventory")
    op.create_index(op.f("ix_items_lifecycle"), "items", ["lifecycle"], unique=False, schema="inventory")
    op.create_index(
        op.f("ix_items_workspace_id"), "items", ["workspace_id"], unique=False, schema="inventory"
    )
    op.create_table(
        "locations",
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("default_privacy_policy", sa.String(length=20), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind != 'system_unspecified' OR parent_id IS NULL", name=op.f("ck_locations_system_root")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "parent_id"],
            ["inventory.locations.workspace_id", "inventory.locations.id"],
            name=op.f("fk_locations_workspace_id_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["inventory.workspaces.id"], name=op.f("fk_locations_workspace_id_workspaces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_locations_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_locations_workspace_id"), "locations", ["workspace_id"], unique=False, schema="inventory"
    )
    op.create_index(
        "uq_location_unspecified",
        "locations",
        ["workspace_id"],
        unique=True,
        schema="inventory",
        postgresql_where=sa.text("kind = 'system_unspecified'"),
        sqlite_where=sa.text("kind = 'system_unspecified'"),
    )
    op.create_table(
        "maintenance_jobs",
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "manifest",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("manifest_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["inventory.users.id"], name=op.f("fk_maintenance_jobs_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["inventory.workspaces.id"],
            name=op.f("fk_maintenance_jobs_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_jobs")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_maintenance_jobs_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_maintenance_jobs_workspace_id"),
        "maintenance_jobs",
        ["workspace_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "media_assets",
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("mime", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("privacy_policy", sa.String(length=20), nullable=False),
        sa.Column("client_preprocessed", sa.Boolean(), nullable=False),
        sa.Column(
            "manifest",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["inventory.workspaces.id"],
            name=op.f("fk_media_assets_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
        sa.UniqueConstraint("object_key", name=op.f("uq_media_assets_object_key")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_media_assets_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_media_assets_workspace_id"),
        "media_assets",
        ["workspace_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "outbox_events",
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("entity_version", sa.BigInteger(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=36), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["inventory.workspaces.id"],
            name=op.f("fk_outbox_events_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_outbox_events_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(
        "ix_outbox_dispatch",
        "outbox_events",
        ["next_attempt_at", "processed_at"],
        unique=False,
        schema="inventory",
    )
    op.create_index(
        op.f("ix_outbox_events_workspace_id"),
        "outbox_events",
        ["workspace_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "reminder_rules",
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"], ["inventory.users.id"], name=op.f("fk_reminder_rules_owner_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["inventory.workspaces.id"],
            name=op.f("fk_reminder_rules_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminder_rules")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_reminder_rules_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_reminder_rules_workspace_id"),
        "reminder_rules",
        ["workspace_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "workspace_memberships",
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["inventory.users.id"], name=op.f("fk_workspace_memberships_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["inventory.workspaces.id"],
            name=op.f("fk_workspace_memberships_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("workspace_id", "user_id", name=op.f("pk_workspace_memberships")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_workspace_memberships_user_id"),
        "workspace_memberships",
        ["user_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "item_aliases",
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("alias", sa.String(length=255), nullable=False),
        sa.Column("normalized_alias", sa.String(length=255), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["inventory.users.id"], name=op.f("fk_item_aliases_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "item_id"],
            ["inventory.items.workspace_id", "inventory.items.id"],
            name=op.f("fk_item_aliases_workspace_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["inventory.workspaces.id"],
            name=op.f("fk_item_aliases_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_aliases")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_item_aliases_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_item_aliases_normalized_alias"),
        "item_aliases",
        ["normalized_alias"],
        unique=False,
        schema="inventory",
    )
    op.create_index(
        op.f("ix_item_aliases_workspace_id"),
        "item_aliases",
        ["workspace_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "lots",
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("lot_kind", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("serial_number", sa.String(length=255), nullable=True),
        sa.Column("manufacturer_batch", sa.String(length=255), nullable=True),
        sa.Column("parent_lot_id", sa.String(length=36), nullable=True),
        sa.Column("acquired_at", sa.Date(), nullable=True),
        sa.Column("manufactured_on", sa.Date(), nullable=True),
        sa.Column("opened_on", sa.Date(), nullable=True),
        sa.Column("expiry_on", sa.Date(), nullable=True),
        sa.Column("expiry_precision", sa.String(length=20), nullable=False),
        sa.Column("expiry_raw_text", sa.String(length=255), nullable=True),
        sa.Column("after_opening_amount", sa.Integer(), nullable=True),
        sa.Column("after_opening_unit", sa.String(length=10), nullable=True),
        sa.Column("effective_expiry_on", sa.Date(), nullable=True),
        sa.Column("expiry_derivation", sa.String(length=30), nullable=False),
        sa.Column("expiry_generation", sa.Integer(), nullable=False),
        sa.Column("privacy_policy", sa.String(length=20), nullable=False),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("attributes_schema_version", sa.String(length=30), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "item_id"],
            ["inventory.items.workspace_id", "inventory.items.id"],
            name=op.f("fk_lots_workspace_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "parent_lot_id"],
            ["inventory.lots.workspace_id", "inventory.lots.id"],
            name=op.f("fk_lots_workspace_id_lots"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["inventory.workspaces.id"], name=op.f("fk_lots_workspace_id_workspaces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lots")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_lots_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_lots_effective_expiry_on"), "lots", ["effective_expiry_on"], unique=False, schema="inventory"
    )
    op.create_index(op.f("ix_lots_item_id"), "lots", ["item_id"], unique=False, schema="inventory")
    op.create_index(
        op.f("ix_lots_serial_number"), "lots", ["serial_number"], unique=False, schema="inventory"
    )
    op.create_index(op.f("ix_lots_workspace_id"), "lots", ["workspace_id"], unique=False, schema="inventory")
    op.create_table(
        "media_bindings",
        sa.Column("media_id", sa.String(length=36), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "media_id"],
            ["inventory.media_assets.workspace_id", "inventory.media_assets.id"],
            name=op.f("fk_media_bindings_workspace_id_media_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["inventory.workspaces.id"],
            name=op.f("fk_media_bindings_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_bindings")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_media_bindings_workspace_id_id")),
        sa.UniqueConstraint(
            "workspace_id",
            "media_id",
            "entity_type",
            "entity_id",
            "role",
            name=op.f("uq_media_bindings_workspace_id_media_id_entity_type_entity_id_role"),
        ),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_media_bindings_entity_id"), "media_bindings", ["entity_id"], unique=False, schema="inventory"
    )
    op.create_index(
        op.f("ix_media_bindings_media_id"), "media_bindings", ["media_id"], unique=False, schema="inventory"
    )
    op.create_index(
        op.f("ix_media_bindings_workspace_id"),
        "media_bindings",
        ["workspace_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "tasks",
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("client_request_id", sa.String(length=36), nullable=False),
        sa.Column("parent_task_id", sa.String(length=36), nullable=True),
        sa.Column("batch_id", sa.String(length=36), nullable=True),
        sa.Column("input_mode", sa.String(length=30), nullable=False),
        sa.Column("input_text", sa.Text(), nullable=True),
        sa.Column(
            "media_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("audio_media_id", sa.String(length=36), nullable=True),
        sa.Column(
            "context",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("requested_privacy", sa.String(length=20), nullable=False),
        sa.Column("effective_privacy", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column("status_version", sa.BigInteger(), nullable=False),
        sa.Column("queue_class", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("config_revision", sa.Integer(), nullable=False),
        sa.Column(
            "config_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("config_snapshot_hash", sa.String(length=80), nullable=False),
        sa.Column("model_route_revision", sa.String(length=100), nullable=False),
        sa.Column("prompt_revision", sa.String(length=80), nullable=False),
        sa.Column("output_schema_version", sa.String(length=30), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("external_calls", sa.Integer(), nullable=False),
        sa.Column("external_cost", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("processing_seconds", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=36), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fencing_token", sa.BigInteger(), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "progress",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("proposal_id", sa.String(length=36), nullable=True),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["inventory.users.id"], name=op.f("fk_tasks_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "audio_media_id"],
            ["inventory.media_assets.workspace_id", "inventory.media_assets.id"],
            name=op.f("fk_tasks_workspace_id_media_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "batch_id"],
            ["inventory.ingestion_batches.workspace_id", "inventory.ingestion_batches.id"],
            name=op.f("fk_tasks_workspace_id_ingestion_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "parent_task_id"],
            ["inventory.tasks.workspace_id", "inventory.tasks.id"],
            name=op.f("fk_tasks_workspace_id_tasks"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["inventory.workspaces.id"], name=op.f("fk_tasks_workspace_id_workspaces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint(
            "workspace_id",
            "created_by",
            "client_request_id",
            name=op.f("uq_tasks_workspace_id_created_by_client_request_id"),
        ),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_tasks_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(
        "ix_tasks_dispatch",
        "tasks",
        ["status", "next_attempt_at", "priority", "created_at"],
        unique=False,
        schema="inventory",
    )
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False, schema="inventory")
    op.create_index(
        op.f("ix_tasks_workspace_id"), "tasks", ["workspace_id"], unique=False, schema="inventory"
    )
    op.create_table(
        "proposals",
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column(
            "actions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "dependencies",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("review_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "source_proposals",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "user_changes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "warnings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["inventory.users.id"], name=op.f("fk_proposals_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "task_id"],
            ["inventory.tasks.workspace_id", "inventory.tasks.id"],
            name=op.f("fk_proposals_workspace_id_tasks"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["inventory.workspaces.id"], name=op.f("fk_proposals_workspace_id_workspaces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposals")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_proposals_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(op.f("ix_proposals_task_id"), "proposals", ["task_id"], unique=False, schema="inventory")
    op.create_index(
        op.f("ix_proposals_workspace_id"), "proposals", ["workspace_id"], unique=False, schema="inventory"
    )
    op.create_table(
        "reminder_occurrences",
        sa.Column("rule_id", sa.String(length=36), nullable=False),
        sa.Column("subject_lot_id", sa.String(length=36), nullable=False),
        sa.Column("generation", sa.String(length=80), nullable=False),
        sa.Column("threshold_key", sa.String(length=50), nullable=False),
        sa.Column("occurrence_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("dedupe_key", sa.String(length=80), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "rule_id"],
            ["inventory.reminder_rules.workspace_id", "inventory.reminder_rules.id"],
            name=op.f("fk_reminder_occurrences_workspace_id_reminder_rules"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "subject_lot_id"],
            ["inventory.lots.workspace_id", "inventory.lots.id"],
            name=op.f("fk_reminder_occurrences_workspace_id_lots"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["inventory.workspaces.id"],
            name=op.f("fk_reminder_occurrences_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminder_occurrences")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_reminder_occurrences_dedupe_key")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_reminder_occurrences_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_reminder_occurrences_occurrence_time"),
        "reminder_occurrences",
        ["occurrence_time"],
        unique=False,
        schema="inventory",
    )
    op.create_index(
        op.f("ix_reminder_occurrences_workspace_id"),
        "reminder_occurrences",
        ["workspace_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "stock_balances",
        sa.Column("lot_id", sa.String(length=36), nullable=False),
        sa.Column("location_id", sa.String(length=36), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("quantity_state", sa.String(length=20), nullable=False),
        sa.Column("last_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_confirmed_by", sa.String(length=36), nullable=True),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(quantity_state IN ('exact','estimated') AND quantity IS NOT NULL) OR (quantity_state IN ('unknown','not_applicable') AND quantity IS NULL)",
            name=op.f("ck_stock_balances_quantity_state"),
        ),
        sa.CheckConstraint("quantity IS NULL OR quantity >= 0", name=op.f("ck_stock_balances_nonnegative")),
        sa.ForeignKeyConstraint(
            ["last_confirmed_by"],
            ["inventory.users.id"],
            name=op.f("fk_stock_balances_last_confirmed_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "location_id"],
            ["inventory.locations.workspace_id", "inventory.locations.id"],
            name=op.f("fk_stock_balances_workspace_id_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "lot_id"],
            ["inventory.lots.workspace_id", "inventory.lots.id"],
            name=op.f("fk_stock_balances_workspace_id_lots"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["inventory.workspaces.id"],
            name=op.f("fk_stock_balances_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_balances")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_stock_balances_workspace_id_id")),
        sa.UniqueConstraint(
            "workspace_id",
            "lot_id",
            "location_id",
            name=op.f("uq_stock_balances_workspace_id_lot_id_location_id"),
        ),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_stock_balances_location_id"),
        "stock_balances",
        ["location_id"],
        unique=False,
        schema="inventory",
    )
    op.create_index(
        op.f("ix_stock_balances_lot_id"), "stock_balances", ["lot_id"], unique=False, schema="inventory"
    )
    op.create_index(
        op.f("ix_stock_balances_workspace_id"),
        "stock_balances",
        ["workspace_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "task_attempts",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("fencing_token", sa.BigInteger(), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=False),
        sa.Column("trust_domain", sa.String(length=20), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column(
            "diagnostics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "task_id"],
            ["inventory.tasks.workspace_id", "inventory.tasks.id"],
            name=op.f("fk_task_attempts_workspace_id_tasks"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["inventory.workspaces.id"],
            name=op.f("fk_task_attempts_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_attempts")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_task_attempts_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_task_attempts_task_id"), "task_attempts", ["task_id"], unique=False, schema="inventory"
    )
    op.create_index(
        op.f("ix_task_attempts_workspace_id"),
        "task_attempts",
        ["workspace_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "proposal_revisions",
        sa.Column("proposal_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "proposal_id"],
            ["inventory.proposals.workspace_id", "inventory.proposals.id"],
            name=op.f("fk_proposal_revisions_workspace_id_proposals"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["inventory.workspaces.id"],
            name=op.f("fk_proposal_revisions_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposal_revisions")),
        sa.UniqueConstraint(
            "proposal_id", "revision", name=op.f("uq_proposal_revisions_proposal_id_revision")
        ),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_proposal_revisions_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_proposal_revisions_workspace_id"),
        "proposal_revisions",
        ["workspace_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "review_receipts",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("proposal_id", sa.String(length=36), nullable=False),
        sa.Column("proposal_revision", sa.Integer(), nullable=False),
        sa.Column("observed_review_hash", sa.String(length=80), nullable=False),
        sa.Column("confirmed_values_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "explicit_changes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("confirmation_source", sa.String(length=20), nullable=False),
        sa.Column("client_request_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["inventory.users.id"], name=op.f("fk_review_receipts_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "proposal_id"],
            ["inventory.proposals.workspace_id", "inventory.proposals.id"],
            name=op.f("fk_review_receipts_workspace_id_proposals"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["inventory.workspaces.id"],
            name=op.f("fk_review_receipts_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_receipts")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_review_receipts_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_review_receipts_workspace_id"),
        "review_receipts",
        ["workspace_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "confirmations",
        sa.Column("proposal_id", sa.String(length=36), nullable=False),
        sa.Column("proposal_revision", sa.Integer(), nullable=False),
        sa.Column("receipt_id", sa.String(length=36), nullable=False),
        sa.Column("operation_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "actions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "dependencies",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("fencing_token", sa.BigInteger(), nullable=False),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "proposal_id"],
            ["inventory.proposals.workspace_id", "inventory.proposals.id"],
            name=op.f("fk_confirmations_workspace_id_proposals"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "receipt_id"],
            ["inventory.review_receipts.workspace_id", "inventory.review_receipts.id"],
            name=op.f("fk_confirmations_workspace_id_review_receipts"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["inventory.workspaces.id"],
            name=op.f("fk_confirmations_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_confirmations")),
        sa.UniqueConstraint("operation_id", name=op.f("uq_confirmations_operation_id")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_confirmations_workspace_id_id")),
        sa.UniqueConstraint(
            "workspace_id",
            "proposal_id",
            "proposal_revision",
            name=op.f("uq_confirmations_workspace_id_proposal_id_proposal_revision"),
        ),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_confirmations_status"), "confirmations", ["status"], unique=False, schema="inventory"
    )
    op.create_index(
        op.f("ix_confirmations_workspace_id"),
        "confirmations",
        ["workspace_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "operations",
        sa.Column("actor_user_id", sa.String(length=36), nullable=False),
        sa.Column("confirmation_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("payload_schema_version", sa.String(length=30), nullable=False),
        sa.Column(
            "normalized_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("request_hash", sa.String(length=80), nullable=False),
        sa.Column("reverses_operation_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["inventory.users.id"], name=op.f("fk_operations_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "confirmation_id"],
            ["inventory.confirmations.workspace_id", "inventory.confirmations.id"],
            name=op.f("fk_operations_workspace_id_confirmations"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "reverses_operation_id"],
            ["inventory.operations.workspace_id", "inventory.operations.id"],
            name=op.f("fk_operations_workspace_id_operations"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["inventory.workspaces.id"], name=op.f("fk_operations_workspace_id_workspaces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operations")),
        sa.UniqueConstraint("confirmation_id", name=op.f("uq_operations_confirmation_id")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_operations_workspace_id_id")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_operations_workspace_id"), "operations", ["workspace_id"], unique=False, schema="inventory"
    )
    op.create_table(
        "operation_entries",
        sa.Column("operation_id", sa.String(length=36), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("before_version", sa.BigInteger(), nullable=True),
        sa.Column("after_version", sa.BigInteger(), nullable=False),
        sa.Column(
            "before_state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "after_state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("quantity_delta", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("unit_id", sa.String(length=30), nullable=True),
        sa.Column("from_location_id", sa.String(length=36), nullable=True),
        sa.Column("to_location_id", sa.String(length=36), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["inventory.operations.id"],
            name=op.f("fk_operation_entries_operation_id_operations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_entries")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_operation_entries_entity_id"),
        "operation_entries",
        ["entity_id"],
        unique=False,
        schema="inventory",
    )
    op.create_index(
        op.f("ix_operation_entries_operation_id"),
        "operation_entries",
        ["operation_id"],
        unique=False,
        schema="inventory",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_operation_entries_operation_id"), table_name="operation_entries", schema="inventory"
    )
    op.drop_index(op.f("ix_operation_entries_entity_id"), table_name="operation_entries", schema="inventory")
    op.drop_table("operation_entries", schema="inventory")
    op.drop_index(op.f("ix_operations_workspace_id"), table_name="operations", schema="inventory")
    op.drop_table("operations", schema="inventory")
    op.drop_index(op.f("ix_confirmations_workspace_id"), table_name="confirmations", schema="inventory")
    op.drop_index(op.f("ix_confirmations_status"), table_name="confirmations", schema="inventory")
    op.drop_table("confirmations", schema="inventory")
    op.drop_index(op.f("ix_review_receipts_workspace_id"), table_name="review_receipts", schema="inventory")
    op.drop_table("review_receipts", schema="inventory")
    op.drop_index(
        op.f("ix_proposal_revisions_workspace_id"), table_name="proposal_revisions", schema="inventory"
    )
    op.drop_table("proposal_revisions", schema="inventory")
    op.drop_index(op.f("ix_task_attempts_workspace_id"), table_name="task_attempts", schema="inventory")
    op.drop_index(op.f("ix_task_attempts_task_id"), table_name="task_attempts", schema="inventory")
    op.drop_table("task_attempts", schema="inventory")
    op.drop_index(op.f("ix_stock_balances_workspace_id"), table_name="stock_balances", schema="inventory")
    op.drop_index(op.f("ix_stock_balances_lot_id"), table_name="stock_balances", schema="inventory")
    op.drop_index(op.f("ix_stock_balances_location_id"), table_name="stock_balances", schema="inventory")
    op.drop_table("stock_balances", schema="inventory")
    op.drop_index(
        op.f("ix_reminder_occurrences_workspace_id"), table_name="reminder_occurrences", schema="inventory"
    )
    op.drop_index(
        op.f("ix_reminder_occurrences_occurrence_time"), table_name="reminder_occurrences", schema="inventory"
    )
    op.drop_table("reminder_occurrences", schema="inventory")
    op.drop_index(op.f("ix_proposals_workspace_id"), table_name="proposals", schema="inventory")
    op.drop_index(op.f("ix_proposals_task_id"), table_name="proposals", schema="inventory")
    op.drop_table("proposals", schema="inventory")
    op.drop_index(op.f("ix_tasks_workspace_id"), table_name="tasks", schema="inventory")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks", schema="inventory")
    op.drop_index("ix_tasks_dispatch", table_name="tasks", schema="inventory")
    op.drop_table("tasks", schema="inventory")
    op.drop_index(op.f("ix_media_bindings_workspace_id"), table_name="media_bindings", schema="inventory")
    op.drop_index(op.f("ix_media_bindings_media_id"), table_name="media_bindings", schema="inventory")
    op.drop_index(op.f("ix_media_bindings_entity_id"), table_name="media_bindings", schema="inventory")
    op.drop_table("media_bindings", schema="inventory")
    op.drop_index(op.f("ix_lots_workspace_id"), table_name="lots", schema="inventory")
    op.drop_index(op.f("ix_lots_serial_number"), table_name="lots", schema="inventory")
    op.drop_index(op.f("ix_lots_item_id"), table_name="lots", schema="inventory")
    op.drop_index(op.f("ix_lots_effective_expiry_on"), table_name="lots", schema="inventory")
    op.drop_table("lots", schema="inventory")
    op.drop_index(op.f("ix_item_aliases_workspace_id"), table_name="item_aliases", schema="inventory")
    op.drop_index(op.f("ix_item_aliases_normalized_alias"), table_name="item_aliases", schema="inventory")
    op.drop_table("item_aliases", schema="inventory")
    op.drop_index(
        op.f("ix_workspace_memberships_user_id"), table_name="workspace_memberships", schema="inventory"
    )
    op.drop_table("workspace_memberships", schema="inventory")
    op.drop_index(op.f("ix_reminder_rules_workspace_id"), table_name="reminder_rules", schema="inventory")
    op.drop_table("reminder_rules", schema="inventory")
    op.drop_index(op.f("ix_outbox_events_workspace_id"), table_name="outbox_events", schema="inventory")
    op.drop_index("ix_outbox_dispatch", table_name="outbox_events", schema="inventory")
    op.drop_table("outbox_events", schema="inventory")
    op.drop_index(op.f("ix_media_assets_workspace_id"), table_name="media_assets", schema="inventory")
    op.drop_table("media_assets", schema="inventory")
    op.drop_index(op.f("ix_maintenance_jobs_workspace_id"), table_name="maintenance_jobs", schema="inventory")
    op.drop_table("maintenance_jobs", schema="inventory")
    op.drop_index(
        "uq_location_unspecified",
        table_name="locations",
        schema="inventory",
        postgresql_where=sa.text("kind = 'system_unspecified'"),
        sqlite_where=sa.text("kind = 'system_unspecified'"),
    )
    op.drop_index(op.f("ix_locations_workspace_id"), table_name="locations", schema="inventory")
    op.drop_table("locations", schema="inventory")
    op.drop_index(op.f("ix_items_workspace_id"), table_name="items", schema="inventory")
    op.drop_index(op.f("ix_items_lifecycle"), table_name="items", schema="inventory")
    op.drop_index(op.f("ix_items_barcode"), table_name="items", schema="inventory")
    op.drop_table("items", schema="inventory")
    op.drop_index(
        op.f("ix_ingestion_batches_workspace_id"), table_name="ingestion_batches", schema="inventory"
    )
    op.drop_table("ingestion_batches", schema="inventory")
    op.drop_index(
        op.f("ix_inbox_notifications_workspace_id"), table_name="inbox_notifications", schema="inventory"
    )
    op.drop_index(
        op.f("ix_inbox_notifications_user_id"), table_name="inbox_notifications", schema="inventory"
    )
    op.drop_table("inbox_notifications", schema="inventory")
    op.drop_index(op.f("ix_field_evidence_workspace_id"), table_name="field_evidence", schema="inventory")
    op.drop_table("field_evidence", schema="inventory")
    op.drop_index(
        op.f("ix_deletion_tombstones_workspace_id"), table_name="deletion_tombstones", schema="inventory"
    )
    op.drop_table("deletion_tombstones", schema="inventory")
    op.drop_table("workspaces", schema="inventory")
    op.drop_table("settings_revisions", schema="inventory")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions", schema="inventory")
    op.drop_index(op.f("ix_sessions_family_id"), table_name="sessions", schema="inventory")
    op.drop_table("sessions", schema="inventory")
    op.drop_table("agreements", schema="inventory")
    op.drop_table("users", schema="inventory")
    op.drop_table("runtime_controls", schema="inventory")
    op.drop_table("model_deployments", schema="inventory")
    op.drop_table("model_cooldowns", schema="inventory")
    op.drop_table("login_attempts", schema="inventory")
    op.drop_table("idempotency_keys", schema="inventory")
    op.drop_table("gpu_slots", schema="inventory")
    op.drop_table("admin_audit", schema="inventory")
    # ### end Alembic commands ###
