export const labels = {
  create: 'Новая',
  existing: 'Существующая',
  exact: 'Точное',
  estimated: 'Примерное',
  unknown: 'Неизвестно',
  not_applicable: 'Учёт присутствия',
  counted: 'По количеству',
  measured: 'По мере',
  individual: 'Уникальный экземпляр',
  untracked: 'Только наличие',
  local_only: 'Только доверенный сервер',
  cloud_allowed: 'Внешняя обработка разрешена',
  day: 'День',
  month: 'Месяц',
  medicine: 'Лекарства',
  document: 'Документы',
  food: 'Продукты',
  clothing: 'Одежда',
  equipment: 'Техника',
  dishes: 'Посуда',
  cosmetics: 'Косметика',
  household: 'Быт',
  hobby: 'Хобби',
  other: 'Другое',
  place: 'Место',
  container: 'Контейнер',
  workspace: 'Весь инвентарь',
  user: 'Только я',
  accepted: 'Принято сервером',
  preparing: 'Подготовка файлов',
  queued: 'В очереди',
  running: 'Обработка',
  retry_wait: 'Ожидает повторной попытки',
  waiting_for_review: 'На проверке',
  applying: 'Сохранение',
  succeeded: 'Завершено',
  failed: 'Ошибка',
  cancelled: 'Отменено',
  expired: 'Истёк срок',
  upload_verified: 'Файлы проверены',
  media: 'Подготовка медиа',
  gatekeeper: 'Первичная проверка',
  privacy_asr: 'Первичная проверка приватности',
  cloud_extraction: 'Распознавание резервной моделью',
  search_ready: 'Результат поиска готов',
  applied: 'Применено',
  editable: 'Ожидает проверки',
  conflict: 'Конфликт изменений',
  revoked: 'Доступ отозван',
  purging: 'Удаление',
  extraction: 'Распознавание',
  candidates: 'Поиск совпадений',
  review_ready: 'Предложение готово',
  apply: 'Применение',
  completed: 'Завершено',
  text: 'Текст',
  photo: 'Фото',
  audio: 'Голос',
  photo_audio: 'Фото и голос',
  manual: 'Ручной ввод',
  active: 'Активно',
  archived: 'В архиве',
  draft: 'Черновик / на проверке',
  receive_stock: 'Поступление',
  move_stock: 'Перемещение',
  consume_stock: 'Расход',
  set_quantity: 'Уточнение остатка',
  update_item: 'Изменение карточки',
  update_lot: 'Изменение партии',
  split_lot: 'Разделение партии',
  merge_lots: 'Объединение партий',
  create_location: 'Создание места',
  move_location: 'Перемещение места',
  update_location: 'Изменение места',
  archive_item: 'Архивация вещи',
  restore_item: 'Восстановление вещи',
  archive_location: 'Архивация места',
  add_alias: 'Добавление названия',
  remove_alias: 'Удаление названия',
  reverse_operation: 'Отмена операции',
  confirm_presence: 'Подтверждение наличия',
}
export const label = (value) => labels[value] || value
